runtime: nodejs18
build_env_variables:
  DB_TYPE: postgres
  DB_HOST: 'ep-black-violet-357358.ap-southeast-1.aws.neon.tech'
  DB_PORT: 5432
  DB_USERNAME: 'khiem.office'
  DB_PASSWORD: 'tgUDlGRe52uK'
  DB_NAME: 'nestle-game'

  #JWT Secret
  JWT_SECRET: secret